name: Releasability status
on:
  workflow_dispatch:
  workflow_run:
    workflows: [Build]  # Name must match the build workflow
    types:
      - completed
    branches:
      - master
      - branch-*

jobs:
  update_releasability_status:
    runs-on: github-ubuntu-latest-s
    name: Releasability status
    permissions:
      id-token: write
      statuses: write
      contents: read
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - uses: SonarSource/gh-action_releasability/releasability-status@c27a275cc9867c8cdfff8ffafcea50957a63503e # v3
        with:
          optional_checks: "Jira,CheckDependencies"
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
